import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

const nunitoSans = Nunito_Sans({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={nunitoSans.className}>
				<Navbar />
				<div className="min-h-[calc(100vh-693.547px)]">
            {children}
            </div>
				<Footer />
			</body>
		</html>
	);
}
